MACHINE LEARNING ASSIGNMENT-1

    NAME       :DHEEPIKA.I
    REGISTER NO:21UAI023
    SUBJECT    :BASICS OF MACHINE LEARNING LABORATORY
    DATE       :05/11/22

In [1]:
#1.IMPORTING LIBRARIES
import numpy as np # numerical data
import pandas as pd #analyzing the data in dataframe and series

In [2]:
#2.iMPORTING DATASET
data=pd.read_csv("C:/Users/User/Downloads/Online_Shopper bml dataset.csv")
data

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [3]:
data.shape

(10, 4)

In [22]:
#SEPARATE INDEPENDENT VALUES
x=data[['Region','Age','Income']].values#data.iloc[:,:-1].values
x

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['India', 40.0, 69600.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

In [4]:
#DEPENDENT VALUES
y=data[['Online Shopper']].values
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [5]:
#Finding missing values
#Find and count the missing values in our dataset
print(data.isnull().sum())

Region            0
Age               1
Income            1
Online Shopper    0
dtype: int64


In [6]:
#drop missing value records- remaining rows are kept as its place
data.dropna(inplace=True)

In [7]:
data

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
5   India  40.0  69600.0            Yes
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [8]:
#simple imputer-filled missing values in numerical
from sklearn.impute import SimpleImputer

In [9]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [10]:
# Fit- we split our data into training and testing adjusts weights according to data values for better accuracy
imputer=imputer.fit(x[:,1:3])

In [11]:
#transform calculate the mean value
x[:,1:3]=imputer.transform(x[:,1:3])
x

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['USA', 45.0, 76533.33333333333],
       ['India', 40.0, 69600.0],
       ['Brazil', 43.77777777777778, 62400.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

In [12]:
#4.ENCODING CATEGORICAL VALUES Label encoder- each unique values it gives an index like 1,2,3
#One hot encoder- take an each index value to add one feature
from sklearn.preprocessing import LabelEncoder

In [13]:
label_encode_x=LabelEncoder()
label_encode_y=LabelEncoder()

In [14]:
x[:,0]=label_encode_x.fit_transform(x[:,0])
x

array([[1, 49.0, 86400.0],
       [0, 32.0, 57600.0],
       [2, 35.0, 64800.0],
       [0, 43.0, 73200.0],
       [2, 45.0, 76533.33333333333],
       [1, 40.0, 69600.0],
       [0, 43.77777777777778, 62400.0],
       [1, 53.0, 94800.0],
       [2, 55.0, 99600.0],
       [1, 42.0, 80400.0]], dtype=object)

In [15]:
label_encode_x.classes_

array(['Brazil', 'India', 'USA'], dtype=object)

In [16]:
y=label_encode_y.fit_transform(y)
y

C:\Users\User\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [17]:
#SPLITING DATASET INTO TRAINING AND TESTING
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [19]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[2 45.0 76533.33333333333]
 [1 49.0 86400.0]
 [0 43.0 73200.0]
 [0 32.0 57600.0]
 [1 53.0 94800.0]
 [2 55.0 99600.0]
 [1 40.0 69600.0]]
[[2 35.0 64800.0]
 [1 42.0 80400.0]
 [0 43.77777777777778 62400.0]]
[1 0 0 1 1 0 1]
[0 1 0]


In [20]:
#6.FEATURE SCALING
from sklearn.preprocessing import StandardScaler

In [21]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
print(x_train)
print(x_test)

[[ 1.32287566 -0.03891021 -0.22960023]
 [ 0.          0.50583275  0.49120535]
 [-1.32287566 -0.31128169 -0.47311563]
 [-1.32287566 -1.80932482 -1.6127677 ]
 [ 0.          1.0505757   1.10486416]
 [ 1.32287566  1.32294718  1.45552633]
 [ 0.         -0.71983891 -0.73611226]]
[[ 1.22474487 -1.38802721 -0.55138018]
 [ 0.          0.45941746  1.40351318]
 [-1.22474487  0.92860975 -0.852133  ]]
